version: '3.7'
services:
  jenkins:
    image: jenkins:latest
    build:
      context: docker
      dockerfile: containers/jenkins/Dockerfile
    container_name: jenkins
    user: jenkins
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - 80:8080
volumes:
  jenkins:
